create table fc.client(
    id integer primary key generated by default as identity,
    full_name text not null,
    price integer not null,
    visit integer not null,
    subscription integer generated always as (price * visit) stored not null,
    group_id integer not null,
    foreign key(group_id) references fc.group(id)
    on delete cascade
)
