create table fc.group(
    id integer primary key generated by default as identity,
    title text not null,
    type_of_occupation text not null,
    timetable_of_classes_id integer not null unique,
    foreign key (timetable_of_classes_id) references fc.timetable_of_classes(id)
    on delete cascade
)
