create table fc.trainer(
    id integer primary key generated by default as identity,
    type_of_activities text not null,
    group_id integer not null unique,
    timetable_of_classes_id integer not null,
    foreign key(group_id) references fc.group(id)
    on delete cascade,
    foreign key(timetable_of_classes_id) references fc.timetable_of_classes(id)
    on delete cascade
)
