create table fc.trainer(
    id integer primary key generated by default as identity,
    full_name text not null,
    group_id integer not null,
    foreign key(group_id) references fc.group(id)
    on delete cascade
)
