create table fc.trainer(
    uuid uuid not null default gen_random_uuid(),
    id integer primary key generated by default as identity,
    full_name fc.fn not null,
    group_id integer not null,
    foreign key(group_id) references fc.group(id)
    on delete cascade
)
