create table fc.visit(
    id integer primary key generated by default as identity,
    date_arrival text not null,
    date_of_departure text not null,
    client_id integer,
    trainer_id integer,
    foreign key (client_id) references fc.client(id)
    on delete cascade,
    foreign key (trainer_id) references fc.trainer(id)
    on delete cascade
)
