create table fc.body_mass_index(
    uuid uuid not null default gen_random_uuid(),
    id integer primary key generated by default as identity,
    weight decimal not null,
    height decimal not null,
    bms decimal not null generated always as (weight / (height * height)) stored
)