create table fc.client(
    uuid uuid not null default gen_random_uuid(),
    id integer primary key generated by default as identity,
    full_name fc.fn not null,
    body_mass_index_id integer not null unique,
    foreign key(body_mass_index_id) references fc.body_mass_index(id)
    on delete cascade
)