create table fc.time(
    uuid uuid not null default gen_random_uuid(),
    id integer primary key generated by default as identity,
    start_time varchar(16) not null,
    end_time varchar(16) not null
)
