create table fc.timetable_of_classes(
    uuid uuid not null default gen_random_uuid(),
    id integer primary key generated by default as identity,
    day_of_the_week_id integer not null,
    time_id integer not null,
    foreign key (day_of_the_week_id) references fc.day_of_the_week(id)
    on delete cascade,
    foreign key (time_id) references fc.time(id)
    on delete cascade
)
